import {
  User,
  Challenge,
  Application,
  Evaluation,
  Pilot,
  LegalTemplate,
  AuditLogEntry,
  NotificationItem,
  Department,
  DepartmentOfficial,
  DocumentAttachment,
  EvaluatorProfile,
  EvaluatorAssignment,
  InterviewMeeting,
  FinalizationDecision,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_dept_01',
    name: 'Dr. Sanjay Deshmukh, IAS',
    email: 'sanjay.deshmukh@maharashtra.gov.in',
    role: 'DEPARTMENT_OFFICIAL',
    departmentId: 'dept_health_01',
    departmentName: 'Department of Public Health, Maharashtra',
    designation: 'Principal Secretary & Mission Director',
    officialRoleInDept: 'ADMIN',
    phone: '+91 98230 11234',
    isVerified: true,
  },
  {
    id: 'usr_dept_02',
    name: 'Pooja Sawant',
    email: 'pooja.sawant@maharashtra.gov.in',
    role: 'DEPARTMENT_OFFICIAL',
    departmentId: 'dept_health_01',
    departmentName: 'Department of Public Health, Maharashtra',
    designation: 'Joint Director (IT & Tele-Medicine)',
    officialRoleInDept: 'MEMBER',
    phone: '+91 98230 44556',
    isVerified: true,
  },
  {
    id: 'usr_dept_pending_01',
    name: 'Rajesh Khadse',
    email: 'rajesh.khadse@maharashtra.gov.in',
    role: 'DEPARTMENT_OFFICIAL',
    departmentId: 'dept_water_pending',
    departmentName: 'Water Supply & Sanitation Department, Maharashtra',
    designation: 'Superintending Engineer (Procurement & IT)',
    officialRoleInDept: 'ADMIN',
    phone: '+91 98220 77611',
    isVerified: false,
  },
  {
    id: 'usr_startup_01',
    name: 'Aarav Patel (Founder & CTO)',
    email: 'aarav@netradiagnostics.in',
    role: 'STARTUP',
    startupName: 'NetraAI Health Systems Pvt Ltd',
    dpiitNumber: 'DIPP-MH-2023-77812',
    dpiitVerified: true,
    gemSellerId: 'GEM-2024-MH-9902',
    phone: '+91 94055 43210',
    isVerified: true,
  },
  {
    id: 'usr_eval_01',
    name: 'Prof. Ananya Kulkarni',
    email: 'ananya.kulkarni@iitb.ac.in',
    role: 'EVALUATOR',
    departmentName: 'IIT Bombay Healthcare AI Center',
    designation: 'Technical Evaluator & Domain Expert',
    phone: '+91 97654 88771',
    isVerified: true,
  },
  {
    id: 'usr_admin_01',
    name: 'Nidhi More, MSInS Nodal Lead',
    email: 'nidhi.more@msins.in',
    role: 'MSINS_ADMIN',
    departmentName: 'Maharashtra State Innovation Society (MSInS)',
    designation: 'Joint CEO & Chief Innovation Officer',
    phone: '+91 98200 55432',
    isVerified: true,
  },
  {
    id: 'usr_val_01',
    name: 'Kishore Shinde, Lead Auditor',
    email: 'k.shinde@stqc.gov.in',
    role: 'INDEPENDENT_VALIDATOR',
    departmentName: 'Standardisation Testing & Quality Certification (STQC)',
    designation: 'Third-Party Independent Certifier',
    phone: '+91 98900 33221',
    isVerified: true,
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: 'chl_01',
    code: 'MSINS-2025-HLTH-001',
    title: 'AI Automated Diabetic Retinopathy & Cataract Triaging in Rural PHCs',
    department: 'Department of Public Health, Government of Maharashtra',
    departmentId: 'dept_health_01',
    sector: 'Healthcare & MedTech',
    problemDescription:
      'Over 68% of diabetic patients in tribal and rural primary health centres (PHCs) in Gadchiroli and Nandurbar lack access to specialist ophthalmologists, resulting in preventable vision loss. Conventional diagnostic equipment is bulky, requires trained doctors, and reports take weeks.',
    outcomeGoal:
      'Field-portable smartphone/edge-AI ophthalmoscope triaging with < 90 seconds screening, > 94% clinical sensitivity against gold-standard fundus reads, and guaranteed offline battery operation in remote PHCs.',
    baselineMetric: 'Mean diagnostic turnaround of 19 days; 1.2 ophthalmologists per 100,000 rural residents.',
    targetOutcome: 'Field-portable point-of-care triaging with < 90 seconds screening, > 94% clinical sensitivity, verifiable offline capability.',
    budgetCeiling: 3500000, // 35 Lakhs INR
    timelineWeeks: 12,
    dataSensitivity: 'HIGH_CONFIDENTIAL',
    gfrRule173Applied: true,
    gfrRule170Applied: true,
    allowNonOfficialEvaluators: true,
    minEvaluatorsRequired: 3,
    eligibilityCustomRequirements:
      'DPIIT recognized entity with edge-AI/computer vision prototype. Prior turnover and prior experience criteria waived pursuant to GFR Rule 173(i). ABDM / DPDP Act 2023 compliance.',
    status: 'APPLICATIONS_OPEN',
    tags: ['AI/ML', 'Tele-Ophthalmology', 'Edge Computing', 'Rural Health', 'Ayushman Bharat'],
    minTpiScore: 70,
    publishedAt: '2025-02-10T10:00:00Z',
    applicationDeadline: '2025-04-15T18:00:00Z',
    creatorId: 'usr_dept_01',
    creatorName: 'Dr. Sanjay Deshmukh, IAS',
    creatorRoleInDept: 'ADMIN',
    applicationsCount: 4,
    pilotsCount: 1,
  },
  {
    id: 'chl_02',
    code: 'MSINS-2025-WAT-002',
    title: 'IoT Real-Time Coliform and Heavy Metal Sensor for Jal Jeevan Schemes',
    department: 'Water Supply & Sanitation Department, Government of Maharashtra',
    departmentId: 'dept_water_pending',
    sector: 'Clean Tech & Water',
    problemDescription:
      'Rural piped water schemes under Har Ghar Jal across 14 drought-prone talukas of Marathwada rely on manual chemical kit testing conducted once every quarter. Microbial contamination surges post-monsoon without real-time detection.',
    outcomeGoal:
      'Continuous automated IoT water quality telemetry sampling turbidity, pH, free chlorine, and coliform surrogates with real-time SCADA/dashboard alerting in < 15 mins to Gram Panchayats.',
    baselineMetric: 'Manual testing every 90 days; bacterial contamination alert latency > 14 days.',
    targetOutcome: 'Continuous IoT telemetry sampling turbidity, pH, free chlorine, and coliform surrogates with real-time SCADA/dashboard alerting in < 15 mins.',
    budgetCeiling: 2800000, // 28 Lakhs INR
    timelineWeeks: 10,
    dataSensitivity: 'MEDIUM_RESTRICTED',
    gfrRule173Applied: true,
    gfrRule170Applied: true,
    allowNonOfficialEvaluators: true,
    minEvaluatorsRequired: 3,
    eligibilityCustomRequirements:
      'DPIIT recognized startup with electrochemical/spectrometric telemetry sensors. Relaxation of turnover under GFR 173(i).',
    status: 'APPLICATIONS_OPEN',
    tags: ['IoT', 'Smart Water', 'CleanTech', 'Jal Jeevan Mission', 'SCADA'],
    minTpiScore: 65,
    publishedAt: '2025-02-15T11:00:00Z',
    applicationDeadline: '2025-04-20T18:00:00Z',
    creatorId: 'usr_dept_pending_01',
    creatorName: 'Rajesh Khadse',
    creatorRoleInDept: 'ADMIN',
    applicationsCount: 2,
    pilotsCount: 0,
  },
  {
    id: 'chl_03',
    code: 'MSINS-2025-AGRI-003',
    title: 'Satellite & Micro-Drone Pink Bollworm Early Infestation Warning',
    department: 'Department of Agriculture, Maharashtra',
    sector: 'AgriTech & Remote Sensing',
    problemDescription:
      'Pink bollworm infestations in cotton crops cause up to 40% yield loss for smallholder farmers across Vidarbha. Conventional ground scouting misses early larval invasion until bolls are irreversibly compromised.',
    baselineMetric: 'Pest identification occurs at stage 3 (after 30% crop damage has occurred).',
    targetOutcome: 'Pre-symptomatic detection via multispectral satellite imagery combined with targeted low-cost drone scans 7 days prior to visual symptoms, achieving 85% accuracy.',
    budgetCeiling: 4200000, // 42 Lakhs INR
    timelineWeeks: 14,
    dataSensitivity: 'LOW_PUBLIC',
    gfrRule173Applied: true,
    gfrRule170Applied: true,
    status: 'PILOT_AWARDED',
    tags: ['Remote Sensing', 'Drones', 'Computer Vision', 'AgriTech', 'Cotton Protection'],
    minTpiScore: 72,
    publishedAt: '2024-11-15T10:00:00Z',
    applicationDeadline: '2025-01-05T18:00:00Z',
    creatorId: 'usr_dept_01',
    creatorName: 'Dept of Agriculture',
    applicationsCount: 5,
    pilotsCount: 1,
  },
  {
    id: 'chl_04',
    code: 'MSINS-2025-URB-004',
    title: 'Adaptive AI Multi-Modal Traffic Signal Optimization for Pune Arterials',
    department: 'Urban Development Department & PMC',
    sector: 'Smart Cities & Mobility',
    problemDescription:
      'Fixed-time and semi-actuated traffic lights at 38 major junctions in Pune result in excessive fuel burn, ambulance hold-ups, and an estimated economic congestion drag of Rs 400 Cr annually.',
    baselineMetric: 'Average peak waiting time of 142 seconds; static green splits oblivious to queue length.',
    targetOutcome: 'Real-time video edge inference adapting green splits dynamically; reducing corridor travel delay by ≥ 22% with emergency vehicle green wave pre-emption.',
    budgetCeiling: 4800000,
    timelineWeeks: 16,
    dataSensitivity: 'MEDIUM_RESTRICTED',
    gfrRule173Applied: true,
    gfrRule170Applied: true,
    status: 'APPLICATIONS_OPEN',
    tags: ['Computer Vision', 'Edge AI', 'Smart Traffic', 'Urban Mobility', 'Green Wave'],
    minTpiScore: 75,
    publishedAt: '2025-02-28T09:00:00Z',
    applicationDeadline: '2025-04-30T18:00:00Z',
    creatorId: 'usr_dept_01',
    creatorName: 'Urban Development Dept',
    applicationsCount: 3,
    pilotsCount: 0,
  },
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app_01',
    challengeId: 'chl_01',
    challengeCode: 'MSINS-2025-HLTH-001',
    challengeTitle: 'AI Automated Diabetic Retinopathy & Cataract Triaging in Rural PHCs',
    startupId: 'usr_startup_01',
    startupName: 'NetraAI Health Systems Pvt Ltd',
    proposalTitle: 'NetraDrishti Edge: Offline-First Smartphone Fundus Screening AI for Tribal PHCs',
    executiveSummary:
      'A handheld 3D-printed smartphone ophthalmoscope attachment paired with a quantized on-device deep neural network that evaluates fundus photographs in 45 seconds without needing cloud internet. Verified on 12,000 annotated eye scans across Indian clinical cohorts.',
    technicalSpecs:
      'On-device TensorFlow Lite model (18MB size) running on Android 10+ devices; 95.2% AUC sensitivity for referable DR; integrates with Ayushman Bharat Digital Mission (ABDM) ABHA health ID.',
    teamCapability:
      'Founders from IIT Bombay and Sankara Nethralaya alumni. 4 published peer-reviewed papers in Lancet Digital Health and Nature Partner Journals. ISO 13485 compliant manufacturing.',
    costBreakdown: 3200000,
    timelineCommitment: 12,
    dpiitCertificate: 'DIPP-MH-2023-77812',
    isDpiitVerified: true,
    gfrTurnoverRelaxed: true,
    gfrEmdRelaxed: true,
    dataSecurityPlan: 'Zero biometric or health data sent unencrypted; on-device processing with DISHA and DPDP Act 2023 local differential privacy hashing.',
    status: 'SELECTED_FOR_PILOT',
    scoreAverage: 89.2,
    submittedAt: '2025-02-18T14:30:00Z',
  },
  {
    id: 'app_02',
    challengeId: 'chl_01',
    challengeCode: 'MSINS-2025-HLTH-001',
    challengeTitle: 'AI Automated Diabetic Retinopathy & Cataract Triaging in Rural PHCs',
    startupId: 'usr_startup_02',
    startupName: 'RetinaCloud Solutions',
    proposalTitle: 'CloudTele-Retina: VSAT-Connected Tele-Ophthalmology Van',
    executiveSummary:
      'Van-mounted fundus cameras streaming raw images to hospital ophthalmologists via SATCOM link.',
    technicalSpecs: 'High-res Canon CR-2 plus satcom satellite modem. Dependent on constant 4G/satellite uplink.',
    teamCapability: 'Medical equipment distributors with 3 technicians.',
    costBreakdown: 3450000,
    timelineCommitment: 14,
    dpiitCertificate: 'DIPP-MH-2024-91022',
    isDpiitVerified: true,
    gfrTurnoverRelaxed: true,
    gfrEmdRelaxed: true,
    status: 'ELIGIBILITY_VERIFIED',
    scoreAverage: 68.5,
    submittedAt: '2025-02-22T11:15:00Z',
  },
  {
    id: 'app_03',
    challengeId: 'chl_02',
    challengeCode: 'MSINS-2025-WAT-002',
    challengeTitle: 'IoT Real-Time Coliform and Heavy Metal Sensor for Jal Jeevan Schemes',
    startupId: 'usr_startup_03',
    startupName: 'JalDrishti Sensors LLP',
    proposalTitle: 'AquaMesh: Electrochemical Microfluidic Fluoride & Coliform Water Monitor',
    executiveSummary:
      'Low-power solar-rechargeable LoRaWAN sensor nodes inserted directly into overhead rural reservoirs, transmitting hourly water purity indices with automated SMS alarms to Gram Panchayats.',
    technicalSpecs: 'Dual wavelength fluorometric spectrometry, IP68 casing, 3-year sensor life before reagent swap.',
    teamCapability: 'PhD graduates from VNIT Nagpur & CSIR-NEERI.',
    costBreakdown: 2600000,
    timelineCommitment: 10,
    dpiitCertificate: 'DIPP-MH-2022-64109',
    isDpiitVerified: true,
    gfrTurnoverRelaxed: true,
    gfrEmdRelaxed: true,
    status: 'SHORTLISTED',
    scoreAverage: 86.0,
    submittedAt: '2025-02-12T09:40:00Z',
  },
];

export const INITIAL_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval_01',
    applicationId: 'app_01',
    challengeId: 'chl_01',
    evaluatorId: 'usr_eval_01',
    evaluatorName: 'Prof. Ananya Kulkarni',
    evaluatorType: 'DOMAIN_EXPERT',
    technicalFeasibility: 24, // out of 25
    teamCapability: 18,        // out of 20
    outcomeAlignment: 24,      // out of 25
    costEfficiency: 14,        // out of 15
    dataSecurityReadiness: 14, // out of 15
    weightedTotal: 94,
    isBlind: false,
    finalized: true,
    qualitativeRemarks:
      'Exceptional edge-computing approach. The offline capability solves the major bottleneck of zero 4G connectivity in tribal tehsils of Gadchiroli. Robust peer-reviewed validation data.',
    evaluatedAt: '2025-02-26T16:00:00Z',
  },
  {
    id: 'eval_02',
    applicationId: 'app_01',
    challengeId: 'chl_01',
    evaluatorId: 'usr_dept_01',
    evaluatorName: 'Dr. Sanjay Deshmukh, IAS',
    evaluatorType: 'DEPARTMENT_OFFICIAL',
    technicalFeasibility: 22,
    teamCapability: 17,
    outcomeAlignment: 23,
    costEfficiency: 13,
    dataSecurityReadiness: 13,
    weightedTotal: 88,
    isBlind: false,
    finalized: true,
    qualitativeRemarks:
      'High alignment with National Health Mission standards. Budget is well within the 35 Lakhs ceiling. The pilot should specifically deploy across 6 PHCs in Aheri and Bhamragad.',
    evaluatedAt: '2025-02-27T11:30:00Z',
  },
  {
    id: 'eval_03',
    applicationId: 'app_01',
    challengeId: 'chl_01',
    evaluatorId: 'usr_admin_01',
    evaluatorName: 'Nidhi More',
    evaluatorType: 'MSINS_REP',
    technicalFeasibility: 21,
    teamCapability: 18,
    outcomeAlignment: 22,
    costEfficiency: 12,
    dataSecurityReadiness: 14,
    weightedTotal: 87,
    isBlind: false,
    finalized: true,
    qualitativeRemarks:
      'Clean GFR 173(i) and 170 compliance. Valid DPIIT certification verified via Startup India API portal. Meets all Maharashtra Startup Policy 2025 sandbox criteria.',
    evaluatedAt: '2025-02-27T15:00:00Z',
  },
];

export const INITIAL_PILOTS: Pilot[] = [
  {
    id: 'plt_01',
    challengeId: 'chl_01',
    challengeTitle: 'AI Automated Diabetic Retinopathy & Cataract Triaging in Rural PHCs',
    applicationId: 'app_01',
    startupId: 'usr_startup_01',
    startupName: 'NetraAI Health Systems Pvt Ltd',
    departmentName: 'Department of Public Health, Maharashtra',
    phase: 'PHASE_1_PILOT', // In Phase 1 active milestone execution
    status: 'IN_PROGRESS',
    totalGrantAmount: 3200000,
    disbursedAmount: 1600000, // 50% disbursed
    contractTemplateVer: 'MSINS-PA-V2.1-IP-OPTION-B',
    eSignedByDepartment: true,
    eSignedByStartup: true,
    eSignedAt: '2025-03-01T10:15:00Z',
    contractHash: 'a7b9c48821fe6317b6a2df89400263f912e5c6a1e7b231da841029c78fe10293',
    startDate: '2025-03-01T00:00:00Z',
    endDate: '2025-05-24T00:00:00Z',
    milestones: [
      {
        id: 'mls_01',
        pilotId: 'plt_01',
        orderIndex: 1,
        title: 'Phase 0 Feasibility Sandbox Calibration',
        description: 'Deploy 6 prototype devices in controlled sandbox with 500 anonymised clinical validation scans.',
        baselineMetric: 'Mean diagnostic turnaround 19 days',
        targetMetric: 'Algorithm triage time < 90 seconds with > 92% sensitivity in sandbox testing',
        currentMetric: '78 seconds average triage, 94.6% sensitivity verified',
        kpiProgressPct: 100,
        trancheAmount: 800000, // 8 Lakhs (25%)
        dueDate: '2025-03-15T00:00:00Z',
        status: 'DISBURSED',
        deliverableUrl: 'https://sahayog.maharashtra.gov.in/docs/pilots/plt_01/m1-sandbox-report.pdf',
        auditNotes: 'Verified by District Health Officer, Gadchiroli. Clean calibration pass.',
        verifiedAt: '2025-03-14T11:00:00Z',
        disbursedAt: '2025-03-16T14:20:00Z',
        pfmsRefId: 'PFMS-MH-TREASURY-2025-881920',
      },
      {
        id: 'mls_02',
        pilotId: 'plt_01',
        orderIndex: 2,
        title: 'Phase 1 Field Deployment across 6 Rural PHCs',
        description: 'Deploy handheld kits at 6 designated PHCs in Gadchiroli; train 18 ASHA workers and Community Health Officers (CHOs).',
        baselineMetric: 'Zero automated screening at PHCs',
        targetMetric: 'Screen ≥ 1,500 high-risk patients; generate digital Ayushman Bharat Health Account (ABHA) linked reports',
        currentMetric: '1,620 rural patients screened; 194 positive early-stage cases referred to District Hospital',
        kpiProgressPct: 100,
        trancheAmount: 800000, // 8 Lakhs (25%)
        dueDate: '2025-04-10T00:00:00Z',
        status: 'DISBURSED',
        deliverableUrl: 'https://sahayog.maharashtra.gov.in/docs/pilots/plt_01/m2-field-log.pdf',
        auditNotes: 'CHO telephonic logs confirmed. 100% ABHA integration successful.',
        verifiedAt: '2025-04-08T09:30:00Z',
        disbursedAt: '2025-04-11T12:00:00Z',
        pfmsRefId: 'PFMS-MH-TREASURY-2025-901412',
      },
      {
        id: 'mls_03',
        pilotId: 'plt_01',
        orderIndex: 3,
        title: 'Independent STQC Clinical Accuracy & Cyber Audit',
        description: 'STQC and Independent Validator double-blind evaluation of 300 random patients re-checked by AIIMS Nagpur ophthalmologists.',
        baselineMetric: 'Diagnostic error rate unmeasured in remote areas',
        targetMetric: 'Discrepancy rate < 4% vs senior clinical ophthalmologist gold standard',
        currentMetric: '2.4% discrepancy rate achieved; zero data leak incidents detected',
        kpiProgressPct: 95,
        trancheAmount: 800000,
        dueDate: '2025-05-05T00:00:00Z',
        status: 'ON_TRACK',
        deliverableUrl: 'https://sahayog.maharashtra.gov.in/docs/pilots/plt_01/m3-stqc-audit.pdf',
        auditNotes: 'Awaiting final certification sign-off from STQC lead auditor.',
      },
      {
        id: 'mls_04',
        pilotId: 'plt_01',
        orderIndex: 4,
        title: 'Phase 2 Scale-Up Transition & GeM Cataloging',
        description: 'Submission of Scale Readiness Dossier, GeM Startup Runway listing specification, and GFR 173(i) Direct Procurement recommendation.',
        baselineMetric: 'Conventional 18-month procurement cycle',
        targetMetric: 'Direct procurement readiness for 350 PHCs across 12 aspirational districts of Maharashtra',
        currentMetric: 'Draft tender specification generated from validated pilot data',
        kpiProgressPct: 40,
        trancheAmount: 800000,
        dueDate: '2025-05-24T00:00:00Z',
        status: 'PENDING',
      },
    ],
    validationRecord: {
      id: 'val_rec_01',
      pilotId: 'plt_01',
      validatorId: 'usr_val_01',
      validatorName: 'Kishore Shinde, STQC Certified Auditor',
      outcomeCertified: true,
      actualMetricAchieved: 'Triage turnaround 68 seconds; 95.8% clinical concordance with AIIMS Nagpur panel.',
      baselineVerified: 'Pre-pilot baseline turnaround: 19 days.',
      targetVerified: 'Exceeded target threshold (< 90 seconds, > 94% sensitivity).',
      certificationNumber: 'MSINS-CERT-2025-089',
      certificateHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      scaleRecommendation: 'DIRECT_DEPARTMENT_PROCUREMENT',
      justificationNotes:
        'The solution demonstrated undeniable clinical efficacy, zero cybersecurity non-compliance under CERT-In standards, and robust GFR 173(i) eligibility. Recommended for immediate scale-up across 350 rural PHCs under NHM funds.',
      gemCatalogReady: true,
      issuedAt: '2025-04-12T16:45:00Z',
    },
  },
];

export const INITIAL_TEMPLATES: LegalTemplate[] = [
  {
    id: 'tpl_01',
    code: 'MSINS-TPL-PRB-V1',
    category: 'PROBLEM_STATEMENT',
    title: 'Outcome-Based Challenge Definition Template',
    version: 'v2.0',
    description:
      'Standardized procurement format replacing rigid input specifications with measurable baselines, outcome KPIs, and risk-bounded pilot budgets.',
    legalReference: 'Maharashtra Startup Policy 2025 & GFR Rule 173(i)',
    clausesSummary: [
      'Clause 1: Definition of Quantifiable Baseline Metric vs Target Outcome',
      'Clause 2: Mandatory Relaxation of Prior Turnover & Experience (GFR 173(i))',
      'Clause 3: Exemption from Earnest Money Deposit (EMD) under GFR Rule 170',
      'Clause 4: Data Sensitivity Tiering & Citizen Privacy Safeguards',
    ],
    contentSnippet: `MODEL PROBLEM STATEMENT (MSInS GRAND CHALLENGE FORMAT)
1. PROBLEM CONTEXT & CITIZEN IMPACT:
[Describe the specific public governance or service delivery bottleneck]

2. BASELINE SPECIFICATION:
Current operational metric: [e.g. 72 hours turnaround time, 18% leak rate]

3. TARGET PERFORMANCE OUTCOME:
Required performance threshold: [e.g. < 4 hours turnaround, < 2% error rate]

4. REGULATORY WAIVERS APPLIED:
Pursuant to GFR 2017 Rule 173(i) and Rule 170, qualifying DPIIT startups are exempt from past turnover and bid security requirements.`,
    downloadFormat: 'DOCX, PDF',
  },
  {
    id: 'tpl_02',
    code: 'MSINS-TPL-RUBRIC-V2',
    category: 'EVALUATION_RUBRIC',
    title: 'Multi-Evaluator Blind Scoring Matrix',
    version: 'v2.2',
    description:
      'Weighted evaluation matrix across 5 objective parameters preventing subjective bias with blinded scoring until final committee consensus.',
    legalReference: 'CVC Public Procurement Guidelines & MSInS Evaluation Protocol',
    clausesSummary: [
      'Technical Feasibility & Innovation Quality (25%)',
      'Team & Founder Execution Capability (20%)',
      'Outcome Metric Alignment & Citizen Value (25%)',
      'Cost Efficiency & Unit Economics at Scale (15%)',
      'Data Privacy, Security & Interoperability Readiness (15%)',
    ],
    contentSnippet: `EVALUATION CRITERIA TABLE:
- Param 1 (25 Pts): Technical Feasibility, TRL Level, Patent/IP uniqueness.
- Param 2 (20 Pts): Core team pedigree, clinical/field advisory board.
- Param 3 (25 Pts): Direct quantitative impact on department baseline metric.
- Param 4 (15 Pts): Rationality of pilot budget & scalable unit pricing.
- Param 5 (15 Pts): CERT-In / DPDP Act compliance, encryption at rest and in transit.`,
    downloadFormat: 'XLSX, PDF',
  },
  {
    id: 'tpl_03',
    code: 'MSINS-TPL-AGREE-V3',
    category: 'PILOT_AGREEMENT',
    title: 'Milestone-Based Sandbox & Pilot Agreement',
    version: 'v3.1',
    description:
      'Tripartite agreement framework between Nodal Agency (MSInS), Implementing Department, and Awarded Startup.',
    legalReference: 'Indian Contract Act 1872 & GFR 2017 Rule 173',
    clausesSummary: [
      'Clause 4: Phased Sandbox Tranches (Phase 0 Feasibility -> Phase 1 Pilot)',
      'Clause 7: 15-Day Milestone Verification & PFMS Treasury Disbursement Guarantee',
      'Clause 9: Mutual Safe-Harbor from Penal Action for Honest Technical Failure',
      'Clause 14: Non-Exclusivity and Direct Transition Rights to Scaled Tender',
    ],
    contentSnippet: `PILOT COOPERATION CONTRACT
BETWEEN: The Governor of Maharashtra acting through [Department],
AND: Maharashtra State Innovation Society (MSInS),
AND: [Selected Startup Pvt Ltd].

RECITALS:
Whereas the Startup has been evaluated under transparent competitive procedures...
PAYMENT DISBURSEMENT:
Upon submission of verification proof by the Designated Officer, payment shall be cleared through PFMS within 15 calendar days.`,
    downloadFormat: 'DOCX, PDF',
  },
  {
    id: 'tpl_04',
    code: 'MSINS-TPL-IP-V1',
    category: 'DATA_IP_CLAUSE',
    title: 'Standard Intellectual Property & Data Ownership Options',
    version: 'v1.3',
    description:
      'Three vetted IP configurations: (Option A) Startup retains all background & foreground IP with perpetual Govt license; (Option B) Govt owns custom datasets, Startup owns algorithm; (Option C) Joint IP for bespoke state assets.',
    legalReference: 'National IPR Policy 2016 & DPDP Act 2023',
    clausesSummary: [
      'Configuration A (Startup Friendly): Startup retains IP; Government receives perpetual, royalty-free, non-exclusive internal use license.',
      'Configuration B (Data Sovereign): Department owns all citizen data and sensor outputs; Startup retains algorithmic IP.',
      'Configuration C (Co-Developed): Joint ownership for custom public infrastructure workflows.',
    ],
    contentSnippet: `IP CONFIGURATION A (RECOMMENDED FOR DEEP-TECH):
The Startup shall retain all right, title, and interest in and to all Pre-existing Intellectual Property and all Project Intellectual Property developed during the Sandbox. The Department is hereby granted a perpetual, irrevocable, royalty-free, non-exclusive license to use the solution across all Maharashtra State administrative jurisdictions.`,
    downloadFormat: 'DOCX, PDF',
  },
  {
    id: 'tpl_05',
    code: 'MSINS-TPL-CYBER-V2',
    category: 'CYBERSECURITY_CHECKLIST',
    title: 'GovTech Sandbox Cybersecurity & Data Residency Checklist',
    version: 'v2.0',
    description:
      'Mandatory pre-deployment security verification covering CERT-In empaneled VAPT audit, local data residency within India, and TLS 1.3 encryption.',
    legalReference: 'CERT-In Directives 2022 & MeitY Cloud Security Mandates',
    clausesSummary: [
      'Requirement 1: Data Localization exclusively within Indian Data Centers (MeitY Empaneled CSPs)',
      'Requirement 2: Static & Dynamic Application Security Testing (SAST/DAST)',
      'Requirement 3: Role-Based Access Control (RBAC) with MFA for administrative credentials',
      'Requirement 4: Audit Log Retention for minimum 180 days with tamper-evident hashing',
    ],
    contentSnippet: `CYBERSECURITY COMPLIANCE AUDIT
- Data Storage: Indian Sovereign Cloud (e.g. AWS Mumbai, Azure Pune, NIC Cloud) [MANDATORY]
- Encryption: AES-256 at rest, TLS 1.3 in transit [MANDATORY]
- API Authentication: HMAC / OAuth 2.0 with rate-limiting [MANDATORY]`,
    downloadFormat: 'PDF, Checklist',
  },
  {
    id: 'tpl_06',
    code: 'MSINS-TPL-EXIT-V1',
    category: 'RISK_EXIT_CLAUSE',
    title: 'No-Fault Pilot Exit & Safe Harbor Provision',
    version: 'v1.1',
    description:
      'Protects startups and innovative government officials from punitive penalties or blacklisting if a breakthrough innovation fails due to technical insurmountable barriers.',
    legalReference: 'MSInS Innovation Safe Harbor Charter 2025',
    clausesSummary: [
      'No-Fault Termination: Either party may terminate with 14 days notice without breach liability',
      'Disbursement Protection: Startup retains funds disbursed for completed milestones',
      'Public Audit Safe-Harbor: Documented technical failure classified as experimental learning',
    ],
    contentSnippet: `SAFE HARBOR COVENANT:
Public officers and participating startups shall not be subjected to vigilance inquiry, liquidated damages, or debarment purely due to the technical failure of an innovative sandbox, provided good-faith execution is documented in the immutable audit trail.`,
    downloadFormat: 'DOCX, PDF',
  },
  {
    id: 'tpl_07',
    code: 'MSINS-TPL-SCALE-V2',
    category: 'PROCUREMENT_TRANSITION',
    title: 'Post-Pilot Procurement Transition & GeM Listing Checklist',
    version: 'v2.1',
    description:
      'Step-by-step procedural roadmap for transitioning a successfully validated pilot into direct departmental procurement under GFR Rule 173(i) or GeM Startup Runway.',
    legalReference: 'GFR 2017 Rule 173(i), GeM Startup Runway SOP & Finance Dept GR',
    clausesSummary: [
      'Step 1: Receipt of Independent Third-Party Validation Certificate',
      'Step 2: Department Sanction Committee approval referencing GFR 173(i)',
      'Step 3: Direct Onboarding to GeM Startup Runway with pre-certified pilot rating',
      'Step 4: Inter-District Adoption Notification via MSInS Portal',
    ],
    contentSnippet: `TRANSITION PROCEDURAL CHECKLIST:
1. Issue Form 12-A: Outcome Certification signed by Independent Third Party.
2. Formulate Commercial Terms based on Pilot Unit Economics.
3. Upload product profile to GeM Startup Runway with MSInS endorsement certificate.
4. Notify all 36 District Collectors for statewide replication.`,
    downloadFormat: 'DOCX, PDF',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log_01',
    action: 'CHALLENGE_PUBLISHED',
    entityType: 'Challenge',
    entityId: 'chl_01',
    actorName: 'Dr. Sanjay Deshmukh, IAS',
    actorRole: 'DEPARTMENT_OFFICIAL',
    policyBasis: 'Maharashtra Startup Policy 2025, Section 4.2',
    hashProof: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    details: 'Challenge MSINS-2025-HLTH-001 created with 35L budget ceiling and GFR 173/170 relaxations enabled.',
    timestamp: '2025-02-10T10:00:00Z',
  },
  {
    id: 'log_02',
    action: 'DPIIT_ELIGIBILITY_AUTO_VERIFIED',
    entityType: 'Application',
    entityId: 'app_01',
    actorName: 'Sahayog DPIIT Gateway (Automated)',
    actorRole: 'MSINS_ADMIN',
    policyBasis: 'GFR 2017 Rule 173(i) & Rule 170',
    hashProof: 'b81920ac34bf99120de840192ea1298418029381029384729182390498120394',
    details: 'Startup NetraAI Health Systems Pvt Ltd verified against DPIIT register (DIPP-MH-2023-77812). Prior turnover and EMD waived.',
    timestamp: '2025-02-18T14:31:10Z',
  },
  {
    id: 'log_03',
    action: 'BLIND_EVALUATION_FINALIZED',
    entityType: 'Evaluation',
    entityId: 'eval_01',
    actorName: 'Prof. Ananya Kulkarni',
    actorRole: 'EVALUATOR',
    policyBasis: 'CVC Public Procurement Matrix 2023',
    hashProof: '9920194820129384019283401928340192834019283401928340192834019283',
    details: 'Independent blind score 94/100 recorded for NetraDrishti Edge. Score unblinded upon committee quorum.',
    timestamp: '2025-02-26T16:05:00Z',
  },
  {
    id: 'log_04',
    action: 'PILOT_CONTRACT_E_SIGNED',
    entityType: 'Contract',
    entityId: 'plt_01',
    actorName: 'Dr. Sanjay Deshmukh & Aarav Patel',
    actorRole: 'DEPARTMENT_OFFICIAL',
    policyBasis: 'Information Technology Act 2000 (e-Sign)',
    hashProof: 'a7b9c48821fe6317b6a2df89400263f912e5c6a1e7b231da841029c78fe10293',
    details: 'Tripartite agreement e-signed with IP Configuration Option A. Total pilot grant 32 Lakhs INR.',
    timestamp: '2025-03-01T10:15:00Z',
  },
  {
    id: 'log_05',
    action: 'PFMS_TRANCHE_DISBURSED',
    entityType: 'Payment',
    entityId: 'mls_01',
    actorName: 'Maharashtra State Treasury / PFMS',
    actorRole: 'MSINS_ADMIN',
    policyBasis: 'Maharashtra Finance Dept GR No. BUD-2024/CR-19',
    hashProof: '3819204810293840192830491823094812039481203948120394812039481203',
    details: 'Rs. 8,00,000 released for Milestone 1 completion to NetraAI account via PFMS Ref PFMS-MH-TREASURY-2025-881920.',
    timestamp: '2025-03-16T14:20:00Z',
  },
  {
    id: 'log_06',
    action: 'INDEPENDENT_VALIDATION_CERTIFIED',
    entityType: 'Validation',
    entityId: 'val_rec_01',
    actorName: 'Kishore Shinde, STQC Certified Auditor',
    actorRole: 'INDEPENDENT_VALIDATOR',
    policyBasis: 'GFR 2017 Rule 173(i) Scaling Protocol',
    hashProof: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    details: 'Formal Certificate MSINS-CERT-2025-089 issued. Recommended for Direct Department Procurement and GeM Startup Runway push.',
    timestamp: '2025-04-12T16:45:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    title: 'New Grand Challenge Published',
    message: 'Department of Public Health published "AI Retinopathy Screening" with GFR 173 relaxation.',
    targetRole: 'STARTUP',
    createdAt: '2025-02-10T10:05:00Z',
    read: false,
    category: 'CHALLENGE',
  },
  {
    id: 'notif_02',
    title: 'Application Received & DPIIT Verified',
    message: 'NetraAI Health Systems application received. Auto-verified via DPIIT registry.',
    targetRole: 'DEPARTMENT_OFFICIAL',
    createdAt: '2025-02-18T14:32:00Z',
    read: false,
    category: 'APPLICATION',
  },
  {
    id: 'notif_03',
    title: 'Blind Evaluation Quorum Reached',
    message: 'All 3 evaluators have finalized scores for Challenge MSINS-2025-HLTH-001. Committee unblinded.',
    targetRole: 'MSINS_ADMIN',
    createdAt: '2025-02-27T15:30:00Z',
    read: false,
    category: 'EVALUATION',
  },
  {
    id: 'notif_04',
    title: 'PFMS Milestone Payment Disbursed',
    message: 'Rs 8,00,000 credited to NetraAI account under Ref PFMS-MH-TREASURY-2025-901412.',
    targetRole: 'STARTUP',
    createdAt: '2025-04-11T12:05:00Z',
    read: true,
    category: 'PAYMENT',
  },
  {
    id: 'notif_05',
    title: 'Third-Party Validation Certificate Issued',
    message: 'STQC certified Outcome Milestone for NetraDrishti. GFR 173 Direct Procurement dossier ready.',
    targetRole: 'DEPARTMENT_OFFICIAL',
    createdAt: '2025-04-12T16:50:00Z',
    read: false,
    category: 'VALIDATION',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept_health_01',
    name: 'Department of Public Health, Government of Maharashtra',
    departmentType: 'STATE_DEPARTMENT',
    address: '5th Floor, Mantralaya Annex, Madame Cama Road',
    district: 'Mumbai City',
    state: 'Maharashtra',
    nodalOfficialName: 'Dr. Sanjay Deshmukh, IAS',
    nodalOfficialDesignation: 'Principal Secretary & Mission Director',
    nodalEmail: 'sanjay.deshmukh@maharashtra.gov.in',
    nodalPhone: '+91 98230 11234',
    isEmailVerified: true,
    isPhoneVerified: true,
    verificationStatus: 'APPROVED',
    verificationNotes: 'Verified via Govt ID, official appointment notification, and Mantralaya Secretariat seal.',
    approvedAt: '2025-01-10T11:00:00Z',
    approvedBy: 'Nidhi More (MSInS Super Admin)',
    badgeIssued: true,
    officials: [
      {
        id: 'usr_dept_01',
        departmentId: 'dept_health_01',
        departmentName: 'Department of Public Health, Government of Maharashtra',
        name: 'Dr. Sanjay Deshmukh, IAS',
        designation: 'Principal Secretary & Mission Director',
        email: 'sanjay.deshmukh@maharashtra.gov.in',
        phone: '+91 98230 11234',
        roleInDept: 'ADMIN',
        verificationStatus: 'VERIFIED',
        govtIdDocName: 'IAS_Appointment_Order_MH_2012.pdf',
        createdAt: '2025-01-10T10:00:00Z',
      },
      {
        id: 'usr_dept_02',
        departmentId: 'dept_health_01',
        departmentName: 'Department of Public Health, Government of Maharashtra',
        name: 'Pooja Sawant',
        designation: 'Joint Director (IT & Tele-Medicine)',
        email: 'pooja.sawant@maharashtra.gov.in',
        phone: '+91 98230 44556',
        roleInDept: 'MEMBER',
        verificationStatus: 'VERIFIED',
        govtIdDocName: 'Govt_Health_Dept_Emp_Card_Pooja.pdf',
        createdAt: '2025-01-15T14:20:00Z',
      },
      {
        id: 'usr_dept_03',
        departmentId: 'dept_health_01',
        departmentName: 'Department of Public Health, Government of Maharashtra',
        name: 'Dr. Amit Shinde',
        designation: 'Nodal Officer (NHM Gadchiroli Pilot)',
        email: 'amit.shinde@maharashtra.gov.in',
        phone: '+91 98230 99887',
        roleInDept: 'MEMBER',
        verificationStatus: 'VERIFIED',
        govtIdDocName: 'Civil_Surgeon_Verification_Gadchiroli.pdf',
        createdAt: '2025-01-20T09:15:00Z',
      },
    ],
    documents: [
      {
        id: 'doc_d1_01',
        ownerType: 'DEPARTMENT',
        ownerId: 'dept_health_01',
        title: 'Nodal Officer Government ID Proof',
        docType: 'GOVT_ID_PROOF',
        fileName: 'IAS_Card_Deshmukh_Verified.pdf',
        fileSize: '1.8 MB',
        verificationStatus: 'VERIFIED',
        uploadedAt: '2025-01-10T10:05:00Z',
      },
      {
        id: 'doc_d1_02',
        ownerType: 'DEPARTMENT',
        ownerId: 'dept_health_01',
        title: 'Department Authorization & Nodal Officer Delegation Letter',
        docType: 'AUTHORIZATION_LETTER',
        fileName: 'Dept_Authorization_Health_MSInS_2025.pdf',
        fileSize: '2.4 MB',
        verificationStatus: 'VERIFIED',
        uploadedAt: '2025-01-10T10:10:00Z',
      },
      {
        id: 'doc_d1_03',
        ownerType: 'DEPARTMENT',
        ownerId: 'dept_health_01',
        title: 'Maharashtra Government Gazette Dept Allocation Notification',
        docType: 'ESTABLISHMENT_GAZETTE',
        fileName: 'GoM_Gazette_PublicHealth_Order_1962_Amended.pdf',
        fileSize: '4.1 MB',
        verificationStatus: 'VERIFIED',
        uploadedAt: '2025-01-10T10:15:00Z',
      },
    ],
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'dept_water_pending',
    name: 'Water Supply & Sanitation Department, Government of Maharashtra',
    departmentType: 'STATE_DEPARTMENT',
    address: 'Ground Floor, CIDCO Bhavan, Sector 11, CBD Belapur',
    district: 'Thane',
    state: 'Maharashtra',
    nodalOfficialName: 'Rajesh Khadse',
    nodalOfficialDesignation: 'Superintending Engineer (Procurement & IT)',
    nodalEmail: 'rajesh.khadse@maharashtra.gov.in',
    nodalPhone: '+91 98220 77611',
    isEmailVerified: true,
    isPhoneVerified: true,
    verificationStatus: 'UNDER_REVIEW',
    verificationNotes: 'Pending MSInS Nodal Lead signoff on department authorization order.',
    badgeIssued: false,
    officials: [
      {
        id: 'usr_dept_pending_01',
        departmentId: 'dept_water_pending',
        departmentName: 'Water Supply & Sanitation Department, Government of Maharashtra',
        name: 'Rajesh Khadse',
        designation: 'Superintending Engineer (Procurement & IT)',
        email: 'rajesh.khadse@maharashtra.gov.in',
        phone: '+91 98220 77611',
        roleInDept: 'ADMIN',
        verificationStatus: 'PENDING',
        govtIdDocName: 'SE_Khadse_Official_Identity.pdf',
        createdAt: '2025-02-05T11:20:00Z',
      },
    ],
    documents: [
      {
        id: 'doc_dw_01',
        ownerType: 'DEPARTMENT',
        ownerId: 'dept_water_pending',
        title: 'Government Identity Card',
        docType: 'GOVT_ID_PROOF',
        fileName: 'Govt_ID_Khadse_SE.pdf',
        fileSize: '2.1 MB',
        verificationStatus: 'PENDING',
        uploadedAt: '2025-02-05T11:25:00Z',
      },
      {
        id: 'doc_dw_02',
        ownerType: 'DEPARTMENT',
        ownerId: 'dept_water_pending',
        title: 'Department Delegation of Financial Powers Order',
        docType: 'AUTHORIZATION_LETTER',
        fileName: 'WSSD_Delegation_Letter_2025.pdf',
        fileSize: '3.0 MB',
        verificationStatus: 'PENDING',
        uploadedAt: '2025-02-05T11:30:00Z',
      },
      {
        id: 'doc_dw_03',
        ownerType: 'DEPARTMENT',
        ownerId: 'dept_water_pending',
        title: 'Department Establishment Notification',
        docType: 'ESTABLISHMENT_GAZETTE',
        fileName: 'WSSD_Gazette_Establishment.pdf',
        fileSize: '3.6 MB',
        verificationStatus: 'PENDING',
        uploadedAt: '2025-02-05T11:35:00Z',
      },
    ],
    createdAt: '2025-02-05T11:20:00Z',
  },
  {
    id: 'dept_pune_district',
    name: 'Collectorate Office & District Innovation Council, Pune',
    departmentType: 'DISTRICT_OFFICE',
    address: 'Old Zilla Parishad Compound, Pune 411001',
    district: 'Pune',
    state: 'Maharashtra',
    nodalOfficialName: 'Meera Kulkarni, IAS',
    nodalOfficialDesignation: 'District Planning Officer',
    nodalEmail: 'meera.kulkarni@nic.in',
    nodalPhone: '+91 94230 45678',
    isEmailVerified: true,
    isPhoneVerified: true,
    verificationStatus: 'APPROVED',
    verificationNotes: 'Approved by MSInS. Verification badge active.',
    approvedAt: '2025-01-18T16:00:00Z',
    approvedBy: 'Nidhi More (MSInS Super Admin)',
    badgeIssued: true,
    officials: [
      {
        id: 'usr_dept_pune_01',
        departmentId: 'dept_pune_district',
        departmentName: 'Collectorate Office & District Innovation Council, Pune',
        name: 'Meera Kulkarni, IAS',
        designation: 'District Planning Officer',
        email: 'meera.kulkarni@nic.in',
        phone: '+91 94230 45678',
        roleInDept: 'ADMIN',
        verificationStatus: 'VERIFIED',
        govtIdDocName: 'IAS_Pune_Posting_Order.pdf',
        createdAt: '2025-01-18T15:00:00Z',
      },
    ],
    documents: [
      {
        id: 'doc_dp_01',
        ownerType: 'DEPARTMENT',
        ownerId: 'dept_pune_district',
        title: 'District Officer ID Card',
        docType: 'GOVT_ID_PROOF',
        fileName: 'NIC_Officer_ID_Pune.pdf',
        fileSize: '1.5 MB',
        verificationStatus: 'VERIFIED',
        uploadedAt: '2025-01-18T15:10:00Z',
      },
    ],
    createdAt: '2025-01-18T15:00:00Z',
  },
];

export const INITIAL_EVALUATOR_POOL: EvaluatorProfile[] = [
  {
    id: 'usr_eval_01',
    name: 'Prof. Ananya Kulkarni',
    email: 'ananya.kulkarni@iitb.ac.in',
    organization: 'IIT Bombay Healthcare AI Center',
    designation: 'Technical Evaluator & Domain Expert',
    type: 'OFFICIAL_GOVT',
    isOfficial: true,
    verificationDoc: 'IITB_Faculty_ID_Emp6671.pdf',
    specialization: ['Healthcare & MedTech', 'Computer Vision', 'Edge AI', 'Clinical Validation'],
    availableForAssignment: true,
  },
  {
    id: 'usr_eval_02',
    name: 'Dr. Vivek Ranade',
    email: 'v.ranade@vjti.ac.in',
    organization: 'Veermata Jijabai Technological Institute (VJTI)',
    designation: 'Professor & Head, IoT Systems Lab',
    type: 'OFFICIAL_GOVT',
    isOfficial: true,
    verificationDoc: 'VJTI_Prof_Order_2021.pdf',
    specialization: ['Clean Tech & Water', 'IoT Telemetry', 'Embedded Systems', 'SCADA'],
    availableForAssignment: true,
  },
  {
    id: 'usr_eval_03',
    name: 'Suhasini Mehta',
    email: 'suhasini.mehta@healthtech-innovations.org',
    organization: 'Digital Health Alliance India',
    designation: 'Senior Medical Device Architect',
    type: 'NON_OFFICIAL_EXPERT',
    isOfficial: false,
    verificationDoc: 'DHAI_Credentials_2024.pdf',
    specialization: ['Medical Device Architecture', 'ISO 13485', 'Regulatory Compliance'],
    availableForAssignment: true,
  },
  {
    id: 'usr_eval_04',
    name: 'Dr. Chetan Bhatt',
    email: 'c.bhatt@coep.ac.in',
    organization: 'COEP Technological University, Pune',
    designation: 'Associate Professor, Department of AI',
    type: 'OFFICIAL_GOVT',
    isOfficial: true,
    verificationDoc: 'COEP_Gazette_Appointment.pdf',
    specialization: ['Smart Cities & Mobility', 'Traffic AI', 'Edge Computing'],
    availableForAssignment: true,
  },
  {
    id: 'usr_eval_05',
    name: 'Kavita Rao',
    email: 'kavita.rao@venture-catalysts.in',
    organization: 'BioValley Innovation Accelerator',
    designation: 'Independent HealthTech Investor & Mentor',
    type: 'NON_OFFICIAL_EXPERT',
    isOfficial: false,
    verificationDoc: 'BioValley_Empanelment.pdf',
    specialization: ['Commercial Viability', 'Financial Audit', 'Unit Economics'],
    availableForAssignment: true,
  },
];

export const INITIAL_EVALUATOR_ASSIGNMENTS: EvaluatorAssignment[] = [
  {
    id: 'asn_01',
    challengeId: 'chl_01',
    evaluatorId: 'usr_eval_01',
    evaluatorName: 'Prof. Ananya Kulkarni',
    evaluatorEmail: 'ananya.kulkarni@iitb.ac.in',
    evaluatorOrganization: 'IIT Bombay Healthcare AI Center',
    evaluatorType: 'OFFICIAL_GOVT',
    isOfficial: true,
    departmentApproved: true,
    status: 'SCORING_COMPLETE',
    assignedAt: '2025-02-20T10:00:00Z',
    completedAt: '2025-02-26T16:00:00Z',
  },
  {
    id: 'asn_02',
    challengeId: 'chl_01',
    evaluatorId: 'usr_dept_01',
    evaluatorName: 'Dr. Sanjay Deshmukh, IAS',
    evaluatorEmail: 'sanjay.deshmukh@maharashtra.gov.in',
    evaluatorOrganization: 'Department of Public Health, Maharashtra',
    evaluatorType: 'OFFICIAL_GOVT',
    isOfficial: true,
    departmentApproved: true,
    status: 'SCORING_COMPLETE',
    assignedAt: '2025-02-20T10:00:00Z',
    completedAt: '2025-02-27T11:30:00Z',
  },
  {
    id: 'asn_03',
    challengeId: 'chl_01',
    evaluatorId: 'usr_eval_03',
    evaluatorName: 'Suhasini Mehta',
    evaluatorEmail: 'suhasini.mehta@healthtech-innovations.org',
    evaluatorOrganization: 'Digital Health Alliance India',
    evaluatorType: 'NON_OFFICIAL_EXPERT',
    isOfficial: false,
    departmentApproved: true,
    status: 'SCORING_COMPLETE',
    assignedAt: '2025-02-20T10:30:00Z',
    completedAt: '2025-02-27T14:45:00Z',
  },
  {
    id: 'asn_04',
    challengeId: 'chl_02',
    evaluatorId: 'usr_eval_02',
    evaluatorName: 'Dr. Vivek Ranade',
    evaluatorEmail: 'v.ranade@vjti.ac.in',
    evaluatorOrganization: 'VJTI Systems Lab',
    evaluatorType: 'OFFICIAL_GOVT',
    isOfficial: true,
    departmentApproved: true,
    status: 'ACCEPTED',
    assignedAt: '2025-02-25T11:00:00Z',
  },
];

export const INITIAL_INTERVIEW_MEETINGS: InterviewMeeting[] = [
  {
    id: 'meet_01',
    challengeId: 'chl_01',
    applicationId: 'app_01',
    startupId: 'usr_startup_01',
    startupName: 'NetraAI Health Systems Pvt Ltd',
    scheduledDate: '2025-02-28',
    scheduledTime: '11:00 AM IST',
    mode: 'ONLINE_LINK',
    meetingLocationOrUrl: 'https://meet.gov.in/msins-health-netraai-eval',
    panelists: [
      'Dr. Sanjay Deshmukh, IAS (Principal Secretary, Health)',
      'Prof. Ananya Kulkarni (IIT Bombay)',
      'Nidhi More (Joint CEO, MSInS)',
    ],
    status: 'COMPLETED',
    notes:
      'Live demonstration of the 3D-printed ophthalmoscope attachment on an Android tablet in airplane mode. The ML model detected pre-annotated severe NPDR and macular edema in under 42 seconds. Team showcased deep understanding of rural PHC operational workflows, solar battery backup, and ABDM ABHA integration. Clean answer on ISO 13485 test logs.',
    recommendation: 'STRONGLY_RECOMMEND',
    assessedAt: '2025-02-28T12:15:00Z',
    assessedBy: 'Dr. Sanjay Deshmukh, IAS',
  },
  {
    id: 'meet_02',
    challengeId: 'chl_01',
    applicationId: 'app_02',
    startupId: 'usr_startup_02',
    startupName: 'RetinaCloud Solutions',
    scheduledDate: '2025-02-28',
    scheduledTime: '02:30 PM IST',
    mode: 'ONLINE_LINK',
    meetingLocationOrUrl: 'https://meet.gov.in/msins-health-retinacloud',
    panelists: [
      'Dr. Sanjay Deshmukh, IAS',
      'Prof. Ananya Kulkarni (IIT Bombay)',
    ],
    status: 'COMPLETED',
    notes:
      'Team proposed van-based equipment that depends entirely on persistent 4G/satellite connection. During the live demo, mock offline mode failed to execute. Hardware footprint is too large for primary health sub-centres in tribal areas.',
    recommendation: 'NOT_RECOMMEND',
    assessedAt: '2025-02-28T15:30:00Z',
    assessedBy: 'Dr. Sanjay Deshmukh, IAS',
  },
];

export const INITIAL_FINALIZATIONS: FinalizationDecision[] = [
  {
    id: 'fin_01',
    challengeId: 'chl_01',
    applicationId: 'app_01',
    startupId: 'usr_startup_01',
    startupName: 'NetraAI Health Systems Pvt Ltd',
    round1Score: 89.2,
    round2Recommendation: 'STRONGLY_RECOMMEND',
    decisionNote:
      'Selected based on highest combined Round 1 technical rubric score (89.2/100) and unanimous Round 2 interview panel recommendation. The solution uniquely provides true offline-first edge AI inference suitable for Gadchiroli and Nandurbar rural PHCs where telecom connectivity is sparse. Costs (INR 32.0 Lakhs) are within the INR 35.0 Lakh ceiling under GFR Rule 173(i) DPIIT exemption.',
    decidedBy: 'Dr. Sanjay Deshmukh, IAS (Principal Secretary & Mission Director)',
    decidedAt: '2025-03-01T09:30:00Z',
    status: 'SELECTED_FOR_PILOT',
    handoffStatus: 'CONTRACTING_PENDING',
  },
];
